# Name: Brayan Chacha Gonzalez 
# 		z1861700
# 		Makefile for assignment 05
CC = g++

TARGET = z1861700_project5

all: z1861700_project5.cpp MemoryChunk.cpp PhysicalMemory.cpp PageTable.cpp
	$(CC) -o $(TARGET) z1861700_project5.cpp MemoryChunk.cpp PhysicalMemory.cpp PageTable.cpp

clean:
	-rm *.o z1861700_project5