# Name: Brayan Chacha Gonzalez 
# 		z1861700
# 		Makefile for assignment 04
make:
	@g++ z1861700_project4_p1.cc -lpthread -o z1861700_project4_p1
	@g++ z1861700_project4_p2.cc -lpthread -o z1861700_project4_p2
clean:
	-rm *.o z1861700_project4_p1
	-rm *.o z1861700_project4_p2
